apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: m597vi8qk-java-springboot 
  janus-idp.io/tekton: m597vi8qk-java-springboot
  backstage.io/kubernetes-id: m597vi8qk-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m597vi8qk-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml