apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: m597vi8qk-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/m597vi8qk-java-springboot-gitops