apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m597vi8qk-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:adb18855a16e51d9f618ba2976fc6a58f25b57c8@sha256:5cb1a741f791b3bd8cee849c9458e9a4990830ab9110e5fd497af896e5409ce2
          name: container-image
